---
sidebar: sidebar 
permalink: task_cli_upgrade_deploy.html 
keywords: administer, administering, cli, deploy, upgrade deploy 
summary: Você pode atualizar uma máquina virtual de utilitário de implantação existente no local usando a interface de linha de comando. 
---
= Atualizar uma instância de implantação
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Você pode atualizar uma máquina virtual de utilitário de implantação existente no local usando a interface de linha de comando.



== Antes de começar

Certifique-se de que Deploy não seja usado para executar outras tarefas durante a atualização. Consulte as notas de versão atuais para obter informações e restrições sobre a atualização do utilitário Deploy.


NOTE: Se tiver uma instância mais antiga do utilitário de administração ONTAP Select Deploy instalada, deverá atualizar para a versão atual. O nó ONTAP Select e o componente ONTAP Select Deploy são atualizados independentemente. link:concept_adm_upgrading_nodes.html["Atualizar os nós de ONTAP Select"^]Consulte para obter mais detalhes.



== Baixe o pacote de upgrade

Para iniciar o processo de atualização, você deve baixar o arquivo de atualização apropriado da máquina virtual Deploy no site de suporte da NetApp. O pacote de atualização está formatado como um único arquivo compactado.

.Passos
. Acesse o link:https://mysupport.netapp.com/site/["NetApp site de suporte"^] usando um navegador da web e escolha *Downloads* no menu Downloads.
. Deslize para baixo e selecione *ONTAP Select Deploy Upgrade*.
. Selecione a versão desejada do pacote de upgrade.
. Reveja o Contrato de Licença de Utilizador final (EULA) e selecione *Accept & continue* (aceitar e continuar).
. Selecione e faça o download do pacote apropriado, respondendo a todas as solicitações conforme necessário para seu ambiente.




== Faça o upload do pacote para a máquina virtual Deploy

Após adquirir o pacote de atualização, você deve carregar o arquivo na máquina virtual Deploy.

.Antes de começar
Você deve ter o arquivo de atualização disponível em sua estação de trabalho local. Você também deve ter a senha da conta de usuário administrador.

.Sobre esta tarefa
Esta tarefa descreve um método para carregar o arquivo na máquina virtual implantar. Pode haver outras opções mais adequadas para o seu ambiente.

.Passos
. Em um terminal de comando em sua estação de trabalho local, use o utilitário scp para carregar o arquivo de imagem para a máquina virtual Deploy.
+
Exemplo

+
....
scp ONTAPdeploy2.12_upgrade.tar.gz admin@10.228.162.221:/home/admin (provide password when prompted)
....


.Resultado
O arquivo de atualização é armazenado no diretório inicial do usuário admin.



== Aplique o pacote de atualização

Após o arquivo de atualização ser carregado na máquina virtual Deploy, você pode aplicar a atualização.

.Antes de começar
Você precisa saber em qual diretório o arquivo de atualização foi colocado na máquina virtual Deploy utility. Além disso, certifique-se de que o Deploy não esteja sendo usado para executar outras tarefas enquanto a atualização estiver em andamento.

.Passos
. Inicie sessão na CLI do utilitário Deploy usando SSH com a conta de administrador.
. Execute a atualização usando o caminho do diretório e o nome do arquivo apropriados:
+
`deploy upgrade -package-path FILEPATH`

+
Exemplo

+
....
deploy upgrade -package-path /home/admin/ONTAPdeploy2.12_upgrade.tar.gz
....


.Depois de terminar
Antes de concluir o procedimento de atualização, você deverá criar um backup da configuração da máquina virtual do Deploy. Além disso, você deve limpar o cache do navegador para poder visualizar as páginas do Deploy recém-criadas.
